puts 'Benvenuto nella lista trucchi GTA San Andreas personale di BOBBIJDJ'
puts 'Quale trucco vorrest vedere?'
cheats = ['                           GENERAL CHEATS','--Happy Bundle','--Immortality','--Suicide','--Never Hungry','--Danny Lazzarin','--No Police','--Expert Driver','--Rispect','--AK-47 to Everyone','                            WEAPONS','--Weapons 1','--Weapons 2','--Weapons 3','--Unlimited Ammo','--Don\'t Worry About Falls','--I\'m a Killer','                            VEICHLE EFFECTS','--I\'m Speed','--I Belive My Car Flies','--I Belive My Boat Flies','                            VEICHLE SPAWN','--Am I a Bull or a Dozer?','--Helicopter!','--I Can Fly... Vertically!!!','--I\'m a RocketMan','--I\'m a Monster... Truck!!!','--It\'s a Four Wheel MotorBike','--I Want to Destroy!!!','--I\'m Really Important','--I\'m a Stunt... Plane!!!','--Land or Air? Both!!!']
cheats.each do |cheatss|
    puts cheatss
end
ortografia = ['Sei pregato di rispettare la mia identica ortografia, ora per punizione devi riavviare questo programma se vuoi usarlo di nuovo']
cheat = gets.chomp
if cheat == 'Happy Bundle'
    puts 'Salute + Armatura + 250.000$'
    puts ''
    puts 'HESOYAM'
elsif cheat == 'Immortality'
    puts 'Vita Infinita'
    puts ''
    puts 'BAGUVIX'
elsif cheat == 'Suicide'
    puts 'CJ si Suicida'
    puts ''
    puts 'GOODBYECRUELWORLD'
elsif cheat == 'Never Hungry'
    puts 'CJ Non Avrà Mai Fame'
    puts ''
    puts 'AEDUWNV'
elsif cheat == 'Danny Lazzarin'
    puts 'CJ Avrà I muscoli Al Massimo'
    puts ''
    puts 'BUFFMEUP'
elsif cheat == 'No Police'
    puts 'CJ Non Sarà Mai Ricercato Dalla Polizia'
    puts ''
    puts 'AEZAKMI'
elsif cheat == 'Expert Driver'
    puts 'Abilità Alla Guida Al Massimo'
    puts ''
    puts 'NATURALTALENT'
elsif cheat == 'Rispect'
    puts 'Rispetto Al Massimo'
    puts ''
    puts 'WORSHIPME'
elsif cheat == 'AK-47 to Everyone'
    puts 'Tutti I Membri Della Gang Avranno Un AK-47'
    puts ''
    puts 'BMTPWHR'
elsif cheat == 'Weapons 1'
    puts 'Tirapugni;Mazza Da Baseball;9mm;Fucile A Pompa;Micro SMG;AK-47;Fucile Semi-Automatico;Lanciarazzi;Molotov;Bomboletta Spray'
    puts ''
    puts 'LXGIWYL'
elsif cheat == 'Weapons 2'
    puts 'Coltello;Dsert Eagle;Fucile A Canne Mozze;Tec-9;M4;Fucile Di Precisione;LanciaFiamme;Granate;Estintore'
    puts ''
    puts 'PROFESSIONALSKIT'
elsif cheat == 'Weapons 3'
    puts 'Motosega;9mm Silenziata;Fulice Da Combattimento;SMG;M4;Fucile Di Precisione;Lanciarazzi A Ricerca Termica;Esplosivi'
    puts ''
    puts 'UZUMYMW'
elsif cheat == 'Unlimited Ammo'
    puts 'Munizioni Infinite'
    puts ''
    puts 'FULLCLLIP'
elsif cheat == 'Don\'t Worry About Falls'
    puts 'CJ Viene Fornito Di Un Paracadute'
    puts ''
    puts 'AIYPWZQP'
elsif cheat == 'I\'m a Killer'
    puts 'Livello Killer In Tutte Le Armi'
    puts ''
    puts 'PROFESSIONALKILLER'
elsif cheat == 'I\'m Speed'
    puts 'Aggiunge Il Nitro A Tutte Le Auto'
    puts ''
    puts 'SPEEDFREAK'
elsif cheat == 'I Belive My Car Flies'
    puts 'Ogni Veicolo Potrà Volare'
    puts ''
    puts 'CHITTYCHITTYBANGBANG'
elsif cheat == 'I Belive My Boat Flies'
    puts 'Tutte Le Barche Decolleranno Dopo Aver Raggiunto Una Certa Velocità'
    puts ''
    puts 'FLYINGFISH'
elsif cheat == 'Am I a Bull or a Dozer?'
    puts 'Fa Comparire Un Bulldozer'
    puts ''
    puts 'ITSALLBULL'
elsif cheat == 'Helicopter!'
    puts 'Fa Comparire Un Elicottero'
    puts ''
    puts 'OHDUDE'
elsif cheat == 'I Can Fly... Vertically!!!'
    puts 'Fa Comparire Un Hydra'
    puts ''
    puts 'JUMPJET'
elsif cheat == 'I\'m a RocketMan'
    puts 'Fa Comparire Un Jetpack'
    puts ''
    puts 'ROCKETMAN'
elsif cheat == 'I\'m a Monster... Truck!!!'
    puts 'Fa Comparire Un Monster Truck'
    puts ''
    puts 'MONSTERMASH'
elsif cheat == 'It\'s a Four Wheel MotorBike'
    puts 'Fa Comparire Un Quad'
    puts ''
    puts 'FOURWHEELFUN'
elsif cheat == 'I Want to Destroy!!!'
    puts 'Fa Comparire Un Carro Armato'
    puts ''
    puts 'AIWPRTON'
elsif cheat == 'I\'m Really Important'
    puts 'Fa Comparire Una Limousine'
    puts ''
    puts 'CELEBRITYSTATUS'
elsif cheat == 'I\'m a Stunt... Plane!!!'
    puts 'Fa Comparire Un Aereo Da Stunt'
    puts ''
    puts 'FLYINGTOSTUNT'
elsif cheat == 'Land or Air? Both!!!'
    puts 'Fa Comparire Un Vortex'
    puts ''
    puts 'KGGGDKP'
elsif cheat == 'GENERAL CHEATS'
    puts '--Happy Bundle'
    puts '--Immortality'
    puts '--Suicide'
    puts '--Never Hungry'
    puts '--Danny Lazzarin'
    puts '--No Police'
    puts '--Expert Driver'
    puts '--Rispect'
    puts '--AK-47 to Everyone'
    cheat = gets.chomp
    if cheat == 'Happy Bundle'
        puts 'Salute + Armatura + 250.000$'
        puts ''
        puts 'HESOYAM'
    elsif cheat == 'Immortality'
        puts 'Vita Infinita'
        puts ''
        puts 'BAGUVIX'
    elsif cheat == 'Suicide'
        puts 'CJ si Suicida'
        puts ''
        puts 'GOODBYECRUELWORLD'
    elsif cheat == 'Never Hungry'
        puts 'CJ Non Avrà Mai Fame'
        puts ''
        puts 'AEDUWNV'
    elsif cheat == 'Danny Lazzarin'
        puts 'CJ Avrà I muscoli Al Massimo'
        puts ''
        puts 'BUFFMEUP'
    elsif cheat == 'No Police'
        puts 'CJ Non Sarà Mai Ricercato Dalla Polizia'
        puts ''
        puts 'AEZAKMI'
    elsif cheat == 'Expert Driver'
        puts 'Abilità Alla Guida Al Massimo'
        puts ''
        puts 'NATURALTALENT'
    elsif cheat == 'Rispect'
        puts 'Rispetto Al Massimo'
        puts ''
        puts 'WORSHIPME'
    elsif cheat == 'AK-47 to Everyone'
        puts 'Tutti I Membri Della Gang Avranno Un AK-47'
        puts ''
        puts 'BMTPWHR'
    end
elsif cheat == 'WEAPONS'
    puts '--Weapons 1'
    puts '--Weapons 2'
    puts '--Weapons 3'
    puts '--Unlimited Ammo'
    puts '--Don\'t Worry About Falls'
    puts '--I\'m a Killer'
    cheat = gets.chomp
    if cheat == 'Weapons 1'
        puts 'Tirapugni;Mazza Da Baseball;9mm;Fucile A Pompa;Micro SMG;AK-47;Fucile Semi-Automatico;Lanciarazzi;Molotov;Bomboletta Spray'
        puts ''
        puts 'LXGIWYL'
    elsif cheat == 'Weapons 2'
        puts 'Coltello;Dsert Eagle;Fucile A Canne Mozze;Tec-9;M4;Fucile Di Precisione;LanciaFiamme;Granate;Estintore'
        puts ''
        puts 'PROFESSIONALSKIT'
    elsif cheat == 'Weapons 3'
        puts 'Motosega;9mm Silenziata;Fulice Da Combattimento;SMG;M4;Fucile Di Precisione;Lanciarazzi A Ricerca Termica;Esplosivi'
        puts ''
        puts 'UZUMYMW'
    elsif cheat == 'Unlimited Ammo'
        puts 'Munizioni Infinite'
        puts ''
        puts 'FULLCLLIP'
    elsif cheat == 'Don\'t Worry About Falls'
        puts 'CJ Viene Fornito Di Un Paracadute'
        puts ''
        puts 'AIYPWZQP'
    elsif cheat == 'I\'m a Killer'
        puts 'Livello Killer In Tutte Le Armi'
        puts ''
        puts 'PROFESSIONALKILLER'
    end
elsif cheat == 'VEICHLE EFFECTS'
    puts '--I\'m Speed'
    puts '--I Belive My Car Flies'
    puts '--I Belive My Boat Flies'
    cheat = gets.chomp
    if cheat == 'I\'m Speed'
        puts 'Aggiunge Il Nitro A Tutte Le Auto'
        puts ''
        puts 'SPEEDFREAK'
    elsif cheat == 'I Belive My Car Flies'
        puts 'Ogni Veicolo Potrà Volare'
        puts ''
        puts 'CHITTYCHITTYBANGBANG'
    elsif cheat == 'I Belive My Boat Flies'
        puts 'Tutte Le Barche Decolleranno Dopo Aver Raggiunto Una Certa Velocità'
        puts ''
        puts 'FLYINGFISH'
    end
elsif cheat == 'VEICHLE SPAWN'
    puts '--Am I a Bull or a Dozer?'
    puts '--Helicopter!'
    puts '--I Can Fly... Vertically!!!'
    puts '--I\'m a RocketMan'
    puts '--I\'m a Monster... Truck!!!'
    puts '--It\'s a Four Wheel MotorBike'
    puts '--I Want to Destroy!!!'
    puts '--I\'m Really Important'
    puts '--I\'m a Stunt... Plane!!!'
    puts '--Land or Air? Both!!!'
    cheat = gets.chomp
    if cheat == 'Am I a Bull or a Dozer?'
        puts 'Fa Comparire Un Bulldozer'
        puts ''
        puts 'ITSALLBULL'
    elsif cheat == 'Helicopter!'
        puts 'Fa Comparire Un Elicottero'
        puts ''
        puts 'OHDUDE'
    elsif cheat == 'I Can Fly... Vertically!!!'
        puts 'Fa Comparire Un Hydra'
        puts ''
        puts 'JUMPJET'
    elsif cheat == 'I\'m a RocketMan'
        puts 'Fa Comparire Un Jetpack'
        puts ''
        puts 'ROCKETMAN'
    elsif cheat == 'I\'m a Monster... Truck!!!'
        puts 'Fa Comparire Un Monster Truck'
        puts ''
        puts 'MONSTERMASH'
    elsif cheat == 'It\'s a Four Wheel MotorBike'
        puts 'Fa Comparire Un Quad'
        puts ''
        puts 'FOURWHEELFUN'
    elsif cheat == 'I Want to Destroy!!!'
        puts 'Fa Comparire Un Carro Armato'
        puts ''
        puts 'AIWPRTON'
    elsif cheat == 'I\'m Really Important'
        puts 'Fa Comparire Una Limousine'
        puts ''
        puts 'CELEBRITYSTATUS'
    elsif cheat == 'I\'m a Stunt... Plane!!!'
        puts 'Fa Comparire Un Aereo Da Stunt'
        puts ''
        puts 'FLYINGTOSTUNT'
    elsif cheat == 'Land or Air? Both!!!'
        puts 'Fa Comparire Un Vortex'
        puts ''
        puts 'KGGGDKP'
    end
end
fine = gets